/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import DAO.ClienteDaoImp;
import DAO.PaisDaoImp;
import Model.Cliente;
import Model.Pais;
import java.util.stream.Stream;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriel
 */
public class TelaCliente extends javax.swing.JFrame {

    private ClienteDaoImp clienteDB;
    private PaisDaoImp paisDB;
    private Pais paisSelecionado;

    /**
     * Creates new form CustomerUI
     */
    public TelaCliente() {
        initComponents();
    }

    TelaCliente(ClienteDaoImp customerDB, PaisDaoImp countryDB) {
        this();

        this.clienteDB = customerDB;
        this.paisDB = countryDB;

        this.paisDB.listPais().forEach(item -> paisComboBox.addItem(item.getNome()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelbt = new javax.swing.JPanel();
        createbt = new javax.swing.JButton();
        listbt = new javax.swing.JButton();
        panelfield = new javax.swing.JPanel();
        namelb = new javax.swing.JLabel();
        nomeTxt = new javax.swing.JTextField();
        agelb = new javax.swing.JLabel();
        agetxt = new javax.swing.JTextField();
        phonelb = new javax.swing.JLabel();
        phonetxt = new javax.swing.JTextField();
        countrylb = new javax.swing.JLabel();
        paisComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listarea = new javax.swing.JTextArea();

        setTitle("Customer Management");

        createbt.setText("Create");
        createbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbtActionPerformed(evt);
            }
        });
        panelbt.add(createbt);

        listbt.setText("List");
        listbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listbtActionPerformed(evt);
            }
        });
        panelbt.add(listbt);

        getContentPane().add(panelbt, java.awt.BorderLayout.PAGE_END);

        panelfield.setLayout(new java.awt.GridLayout(4, 2));

        namelb.setText("Name");
        panelfield.add(namelb);

        nomeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTxtActionPerformed(evt);
            }
        });
        panelfield.add(nomeTxt);

        agelb.setText("Age");
        panelfield.add(agelb);
        panelfield.add(agetxt);

        phonelb.setText("Phone");
        panelfield.add(phonelb);
        panelfield.add(phonetxt);

        countrylb.setText("Country");
        panelfield.add(countrylb);

        paisComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisComboBoxActionPerformed(evt);
            }
        });
        panelfield.add(paisComboBox);

        getContentPane().add(panelfield, java.awt.BorderLayout.NORTH);

        listarea.setColumns(20);
        listarea.setRows(5);
        jScrollPane1.setViewportView(listarea);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listbtActionPerformed

        listarea.setText(clienteDB.list().toString());
    }//GEN-LAST:event_listbtActionPerformed

    private void nomeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTxtActionPerformed

    private void createbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbtActionPerformed
        Cliente c = new Cliente();

        try {
            c.setNome(nomeTxt.getText());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        try {
            c.setPais(paisSelecionado);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        try {
            c.setTelefone(phonetxt.getText());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        c.setIdade(new Integer(agetxt.getText()));
        c.setLimiteCredito(0);

        try {
            clienteDB.create(c);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_createbtActionPerformed

    private void paisComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisComboBoxActionPerformed

        for (Pais currentCountry : paisDB.listPais()) {
            if (currentCountry.getNome().equalsIgnoreCase((String) paisComboBox.getSelectedItem())) {
                paisSelecionado = currentCountry;
            }
        }
    }//GEN-LAST:event_paisComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agelb;
    private javax.swing.JTextField agetxt;
    private javax.swing.JLabel countrylb;
    private javax.swing.JButton createbt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea listarea;
    private javax.swing.JButton listbt;
    private javax.swing.JLabel namelb;
    private javax.swing.JTextField nomeTxt;
    private javax.swing.JComboBox<String> paisComboBox;
    private javax.swing.JPanel panelbt;
    private javax.swing.JPanel panelfield;
    private javax.swing.JLabel phonelb;
    private javax.swing.JTextField phonetxt;
    // End of variables declaration//GEN-END:variables
}
