/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import DAO.ClienteDAO;
import DataBase.ClienteDaoImp;
import DataBase.PaisDaoImp;
import Data.Cliente;
import Data.Pais;
import java.util.stream.Stream;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriel
 */
public class TelaCliente extends javax.swing.JFrame {

    private ClienteDaoImp clienteDB;
    private PaisDaoImp paisDB;
    private Pais paisSelecionado;

    /**
     * Creates new form CustomerUI
     */
    public TelaCliente() {
        initComponents();
    }

    TelaCliente(ClienteDaoImp customerDB, PaisDaoImp countryDB) {
        this();

        this.clienteDB = customerDB;
        this.paisDB = countryDB;

       // this.paisDB.listPais().forEach(item -> paisComboBox.addItem(item.getNome()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelbt = new javax.swing.JPanel();
        createButton = new javax.swing.JButton();
        listbt = new javax.swing.JButton();
        panelfield = new javax.swing.JPanel();
        namelb = new javax.swing.JLabel();
        nomeTxt = new javax.swing.JTextField();
        agelb = new javax.swing.JLabel();
        idadeTxt = new javax.swing.JTextField();
        phonelb = new javax.swing.JLabel();
        telefoneTxt = new javax.swing.JTextField();
        countrylb = new javax.swing.JLabel();
        paisComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listarea = new javax.swing.JTextArea();

        setTitle("Customer Management");

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        panelbt.add(createButton);

        listbt.setText("List");
        listbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listbtActionPerformed(evt);
            }
        });
        panelbt.add(listbt);

        getContentPane().add(panelbt, java.awt.BorderLayout.PAGE_END);

        panelfield.setLayout(new java.awt.GridLayout(4, 2));

        namelb.setText("Nome");
        panelfield.add(namelb);

        nomeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTxtActionPerformed(evt);
            }
        });
        panelfield.add(nomeTxt);

        agelb.setText("Idade");
        panelfield.add(agelb);
        panelfield.add(idadeTxt);

        phonelb.setText("Telefone");
        panelfield.add(phonelb);
        panelfield.add(telefoneTxt);

        countrylb.setText("País");
        panelfield.add(countrylb);

        paisComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisComboBoxActionPerformed(evt);
            }
        });
        panelfield.add(paisComboBox);

        getContentPane().add(panelfield, java.awt.BorderLayout.NORTH);

        listarea.setColumns(20);
        listarea.setRows(5);
        jScrollPane1.setViewportView(listarea);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listbtActionPerformed

        
    }//GEN-LAST:event_listbtActionPerformed

    private void nomeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTxtActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        Cliente cliente = new Cliente();
        ClienteDAO clienteDAO = new ClienteDAO();
        
        try {
            cliente.setNome(nomeTxt.getText());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        try {
            cliente.setPais(paisSelecionado);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        try {
            cliente.setTelefone(telefoneTxt.getText());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        cliente.setIdade(new Integer(idadeTxt.getText()));
        cliente.setLimiteCredito(0);

        try {
            clienteDAO.create(cliente);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void paisComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisComboBoxActionPerformed

        /*for (Pais currentCountry : paisDB.listPais()) {
            if (currentCountry.getNome().equalsIgnoreCase((String) paisComboBox.getSelectedItem())) {
                paisSelecionado = currentCountry;
            }
        }*/
    }//GEN-LAST:event_paisComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agelb;
    private javax.swing.JLabel countrylb;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField idadeTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea listarea;
    private javax.swing.JButton listbt;
    private javax.swing.JLabel namelb;
    private javax.swing.JTextField nomeTxt;
    private javax.swing.JComboBox<String> paisComboBox;
    private javax.swing.JPanel panelbt;
    private javax.swing.JPanel panelfield;
    private javax.swing.JLabel phonelb;
    private javax.swing.JTextField telefoneTxt;
    // End of variables declaration//GEN-END:variables
}
