/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.PaisDAO;
import DataBase.PaisDaoImp;
import Data.Pais;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriel
 */
public class TelaPais extends javax.swing.JFrame {

    private PaisDaoImp paisDB;
    
    /**
     * Creates new form CountryUI
     */
    public TelaPais() {
        initComponents();
    }

    TelaPais(PaisDaoImp countryDB) {
        this();
        
        this.paisDB = countryDB;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        createbt = new javax.swing.JButton();
        listbt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        namelb = new javax.swing.JLabel();
        nomeTxt = new javax.swing.JTextField();
        acronlb = new javax.swing.JLabel();
        siglaTxt = new javax.swing.JTextField();
        phonedigitslb = new javax.swing.JLabel();
        telefoneDigitoTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listarea = new javax.swing.JTextArea();

        setTitle("Country Management");

        createbt.setText("Create");
        createbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbtActionPerformed(evt);
            }
        });
        jPanel1.add(createbt);

        listbt.setText("List");
        listbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listbtActionPerformed(evt);
            }
        });
        jPanel1.add(listbt);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridLayout(3, 2));

        namelb.setText("Name");
        jPanel2.add(namelb);
        jPanel2.add(nomeTxt);

        acronlb.setText("Sigla");
        jPanel2.add(acronlb);
        jPanel2.add(siglaTxt);

        phonedigitslb.setText("Número de dígitos do telefone");
        jPanel2.add(phonedigitslb);
        jPanel2.add(telefoneDigitoTxt);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        listarea.setColumns(20);
        listarea.setRows(5);
        jScrollPane1.setViewportView(listarea);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listbtActionPerformed
        
    }//GEN-LAST:event_listbtActionPerformed

    private void createbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbtActionPerformed
        
        Pais pais = new Pais();
        PaisDAO paisDAO = new PaisDAO();
        
        try {
            pais.setNome(nomeTxt.getText());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        try {
            pais.setSigla(siglaTxt.getText());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        try {
            pais.setDigitos(Integer.parseInt(telefoneDigitoTxt.getText()));

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
        try {
            paisDAO.createPais(pais);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_createbtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acronlb;
    private javax.swing.JButton createbt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea listarea;
    private javax.swing.JButton listbt;
    private javax.swing.JLabel namelb;
    private javax.swing.JTextField nomeTxt;
    private javax.swing.JLabel phonedigitslb;
    private javax.swing.JTextField siglaTxt;
    private javax.swing.JTextField telefoneDigitoTxt;
    // End of variables declaration//GEN-END:variables
}
